version: '2'
services:
    jhipster5-couchbase:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - TYPE=MASTER
            - BUCKET=jhipster5
    jhipster5-couchbase-node:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        environment:
            - TYPE=WORKER
            - BUCKET=jhipster5
            - COUCHBASE_MASTER=jhipster5-couchbase
            - AUTO_REBALANCE=false
